DROP DATABASE UPLOAD;
create DATABASE UPLOAD;
USE UPLOAD;

CREATE TABLE USER(
    ID int NOT NULL AUTO_INCREMENT,
    EMAIL varchar(255) NOT NULL,
    PASSWORD varchar(255) NOT NULL,
    ROLE varchar(2555) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY unique_email (EMAIL)
);

CREATE TABLE POST(
    ID int NOT NULL AUTO_INCREMENT ,
    USERID int NOT NULL,
    TITLE varchar(255) NOT NULL,
    CONTENT varchar(1000) NOT NULL,
    Foreign Key (USERID) references USER(ID) ON DELETE CASCADE,
    PRIMARY KEY(ID),
    UNIQUE KEY(USERID,TITLE) 
);