POST  http://localhost:80/Login
Content-Type: application/json

{
    "User":{
        "Email":"kyler.daybell@gmail.com",
        "Password":"kyler",
        "Authorization":"admin"
    }
}

###

GET http://localhost:80/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imt5bGVyLmRheWJlbGxAZ21haWwuY29tIiwicGFzc3dvcmQiOiJreWxlciIsImF1dGhvcml6YXRpb24iOiJhZG1pbiIsImlhdCI6MTU4NjA2NDY5Mn0.lI_gsvUopb0-1pIxko1-mSnjmKNGRqv6YrdCLmPlKr4
